/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MySocietiesRouteImport } from './routes/my-societies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocietyPulseRouteImport } from './routes/society-pulse'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CallRoomIdRouteImport } from './routes/call.$roomId'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as JoinRoomIdRouteImport } from './routes/join.$roomId'
import { Route as RecapsRecapIdRouteImport } from './routes/recaps.$recapId'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as SocietiesIndexRouteImport } from './routes/societies.index'
import { Route as SocietiesSocietyIdRouteImport } from './routes/societies.$societyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MySocietiesRoute = MySocietiesRouteImport.update({
  id: '/my-societies',
  path: '/my-societies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyPulseRoute = SocietyPulseRouteImport.update({
  id: '/society-pulse',
  path: '/society-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoomIdRoute = CallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomIdRoute = JoinRoomIdRouteImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapsRecapIdRoute = RecapsRecapIdRouteImport.update({
  id: '/recaps/$recapId',
  path: '/recaps/$recapId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesIndexRoute = SocietiesIndexRouteImport.update({
  id: '/societies/',
  path: '/societies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesSocietyIdRoute = SocietiesSocietyIdRouteImport.update({
  id: '/societies/$societyId',
  path: '/societies/$societyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/inbox': typeof InboxRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/recaps/$recapId': typeof RecapsRecapIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/calls/': typeof CallsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/societies/': typeof SocietiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/inbox': typeof InboxRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/recaps/$recapId': typeof RecapsRecapIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/calls': typeof CallsIndexRoute
  '/events': typeof EventsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/societies': typeof SocietiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/inbox': typeof InboxRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/recaps/$recapId': typeof RecapsRecapIdRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/calls/': typeof CallsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/societies/': typeof SocietiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committee'
    | '/communications'
    | '/inbox'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/call/$roomId'
    | '/events/$eventId'
    | '/join/$roomId'
    | '/recaps/$recapId'
    | '/requests/$requestId'
    | '/societies/$societyId'
    | '/calls/'
    | '/events/'
    | '/requests/'
    | '/societies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committee'
    | '/communications'
    | '/inbox'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/call/$roomId'
    | '/events/$eventId'
    | '/join/$roomId'
    | '/recaps/$recapId'
    | '/requests/$requestId'
    | '/societies/$societyId'
    | '/calls'
    | '/events'
    | '/requests'
    | '/societies'
  id:
    | '__root__'
    | '/'
    | '/committee'
    | '/communications'
    | '/inbox'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/call/$roomId'
    | '/events/$eventId'
    | '/join/$roomId'
    | '/recaps/$recapId'
    | '/requests/$requestId'
    | '/societies/$societyId'
    | '/calls/'
    | '/events/'
    | '/requests/'
    | '/societies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteeRoute: typeof CommitteeRoute
  CommunicationsRoute: typeof CommunicationsRoute
  InboxRoute: typeof InboxRoute
  MySocietiesRoute: typeof MySocietiesRoute
  SettingsRoute: typeof SettingsRoute
  SocietyPulseRoute: typeof SocietyPulseRoute
  WelcomeRoute: typeof WelcomeRoute
  CallRoomIdRoute: typeof CallRoomIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  JoinRoomIdRoute: typeof JoinRoomIdRoute
  RecapsRecapIdRoute: typeof RecapsRecapIdRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  SocietiesSocietyIdRoute: typeof SocietiesSocietyIdRoute
  CallsIndexRoute: typeof CallsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SocietiesIndexRoute: typeof SocietiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-societies': {
      id: '/my-societies'
      path: '/my-societies'
      fullPath: '/my-societies'
      preLoaderRoute: typeof MySocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/society-pulse': {
      id: '/society-pulse'
      path: '/society-pulse'
      fullPath: '/society-pulse'
      preLoaderRoute: typeof SocietyPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$roomId': {
      id: '/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof CallRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomId': {
      id: '/join/$roomId'
      path: '/join/$roomId'
      fullPath: '/join/$roomId'
      preLoaderRoute: typeof JoinRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recaps/$recapId': {
      id: '/recaps/$recapId'
      path: '/recaps/$recapId'
      fullPath: '/recaps/$recapId'
      preLoaderRoute: typeof RecapsRecapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies/': {
      id: '/societies/'
      path: '/societies'
      fullPath: '/societies/'
      preLoaderRoute: typeof SocietiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies/$societyId': {
      id: '/societies/$societyId'
      path: '/societies/$societyId'
      fullPath: '/societies/$societyId'
      preLoaderRoute: typeof SocietiesSocietyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteeRoute: CommitteeRoute,
  CommunicationsRoute: CommunicationsRoute,
  InboxRoute: InboxRoute,
  MySocietiesRoute: MySocietiesRoute,
  SettingsRoute: SettingsRoute,
  SocietyPulseRoute: SocietyPulseRoute,
  WelcomeRoute: WelcomeRoute,
  CallRoomIdRoute: CallRoomIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  RecapsRecapIdRoute: RecapsRecapIdRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  SocietiesSocietyIdRoute: SocietiesSocietyIdRoute,
  CallsIndexRoute: CallsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SocietiesIndexRoute: SocietiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
