/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as MySocietiesRouteImport } from './routes/my-societies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocietyPulseRouteImport } from './routes/society-pulse'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as SocietiesIndexRouteImport } from './routes/societies.index'
import { Route as SocietiesSocietyIdRouteImport } from './routes/societies.$societyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const MySocietiesRoute = MySocietiesRouteImport.update({
  id: '/my-societies',
  path: '/my-societies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyPulseRoute = SocietyPulseRouteImport.update({
  id: '/society-pulse',
  path: '/society-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesIndexRoute = SocietiesIndexRouteImport.update({
  id: '/societies/',
  path: '/societies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesSocietyIdRoute = SocietiesSocietyIdRouteImport.update({
  id: '/societies/$societyId',
  path: '/societies/$societyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/events/': typeof EventsIndexRoute
  '/societies/': typeof SocietiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/events': typeof EventsIndexRoute
  '/societies': typeof SocietiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/communications': typeof CommunicationsRoute
  '/my-societies': typeof MySocietiesRoute
  '/settings': typeof SettingsRoute
  '/society-pulse': typeof SocietyPulseRoute
  '/welcome': typeof WelcomeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRoute
  '/events/': typeof EventsIndexRoute
  '/societies/': typeof SocietiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committee'
    | '/communications'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/events/$eventId'
    | '/societies/$societyId'
    | '/events/'
    | '/societies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committee'
    | '/communications'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/events/$eventId'
    | '/societies/$societyId'
    | '/events'
    | '/societies'
  id:
    | '__root__'
    | '/'
    | '/committee'
    | '/communications'
    | '/my-societies'
    | '/settings'
    | '/society-pulse'
    | '/welcome'
    | '/events/$eventId'
    | '/societies/$societyId'
    | '/events/'
    | '/societies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteeRoute: typeof CommitteeRoute
  CommunicationsRoute: typeof CommunicationsRoute
  MySocietiesRoute: typeof MySocietiesRoute
  SettingsRoute: typeof SettingsRoute
  SocietyPulseRoute: typeof SocietyPulseRoute
  WelcomeRoute: typeof WelcomeRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  SocietiesSocietyIdRoute: typeof SocietiesSocietyIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SocietiesIndexRoute: typeof SocietiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-societies': {
      id: '/my-societies'
      path: '/my-societies'
      fullPath: '/my-societies'
      preLoaderRoute: typeof MySocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/society-pulse': {
      id: '/society-pulse'
      path: '/society-pulse'
      fullPath: '/society-pulse'
      preLoaderRoute: typeof SocietyPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies/': {
      id: '/societies/'
      path: '/societies'
      fullPath: '/societies/'
      preLoaderRoute: typeof SocietiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies/$societyId': {
      id: '/societies/$societyId'
      path: '/societies/$societyId'
      fullPath: '/societies/$societyId'
      preLoaderRoute: typeof SocietiesSocietyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteeRoute: CommitteeRoute,
  CommunicationsRoute: CommunicationsRoute,
  MySocietiesRoute: MySocietiesRoute,
  SettingsRoute: SettingsRoute,
  SocietyPulseRoute: SocietyPulseRoute,
  WelcomeRoute: WelcomeRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  SocietiesSocietyIdRoute: SocietiesSocietyIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  SocietiesIndexRoute: SocietiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
