/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMySocietiesRouteImport } from './routes/_authenticated/my-societies'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSocietyPulseRouteImport } from './routes/_authenticated/society-pulse'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthenticatedCallRoomIdRouteImport } from './routes/_authenticated/call.$roomId'
import { Route as AuthenticatedCallsIndexRouteImport } from './routes/_authenticated/calls.index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedRecapsRecapIdRouteImport } from './routes/_authenticated/recaps.$recapId'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedSocietiesIndexRouteImport } from './routes/_authenticated/societies.index'
import { Route as AuthenticatedSocietiesSocietyIdRouteImport } from './routes/_authenticated/societies.$societyId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySocietiesRoute =
  AuthenticatedMySocietiesRouteImport.update({
    id: '/my-societies',
    path: '/my-societies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocietyPulseRoute =
  AuthenticatedSocietyPulseRouteImport.update({
    id: '/society-pulse',
    path: '/society-pulse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallRoomIdRoute = AuthenticatedCallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsIndexRoute = AuthenticatedCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecapsRecapIdRoute =
  AuthenticatedRecapsRecapIdRouteImport.update({
    id: '/recaps/$recapId',
    path: '/recaps/$recapId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocietiesIndexRoute =
  AuthenticatedSocietiesIndexRouteImport.update({
    id: '/societies/',
    path: '/societies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocietiesSocietyIdRoute =
  AuthenticatedSocietiesSocietyIdRouteImport.update({
    id: '/societies/$societyId',
    path: '/societies/$societyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-societies': typeof AuthenticatedMySocietiesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/society-pulse': typeof AuthenticatedSocietyPulseRoute
  '/join/$code': typeof JoinCodeRoute
  '/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/recaps/$recapId': typeof AuthenticatedRecapsRecapIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/societies/$societyId': typeof AuthenticatedSocietiesSocietyIdRoute
  '/calls/': typeof AuthenticatedCallsIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/societies/': typeof AuthenticatedSocietiesIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-societies': typeof AuthenticatedMySocietiesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/society-pulse': typeof AuthenticatedSocietyPulseRoute
  '/join/$code': typeof JoinCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/recaps/$recapId': typeof AuthenticatedRecapsRecapIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/societies/$societyId': typeof AuthenticatedSocietiesSocietyIdRoute
  '/calls': typeof AuthenticatedCallsIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/societies': typeof AuthenticatedSocietiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/my-societies': typeof AuthenticatedMySocietiesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/society-pulse': typeof AuthenticatedSocietyPulseRoute
  '/join/$code': typeof JoinCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/call/$roomId': typeof AuthenticatedCallRoomIdRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/recaps/$recapId': typeof AuthenticatedRecapsRecapIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/societies/$societyId': typeof AuthenticatedSocietiesSocietyIdRoute
  '/_authenticated/calls/': typeof AuthenticatedCallsIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/societies/': typeof AuthenticatedSocietiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/admin'
    | '/committee'
    | '/communications'
    | '/inbox'
    | '/my-societies'
    | '/onboarding'
    | '/settings'
    | '/society-pulse'
    | '/join/$code'
    | '/call/$roomId'
    | '/events/$eventId'
    | '/recaps/$recapId'
    | '/requests/$requestId'
    | '/societies/$societyId'
    | '/calls/'
    | '/events/'
    | '/requests/'
    | '/societies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/admin'
    | '/committee'
    | '/communications'
    | '/inbox'
    | '/my-societies'
    | '/onboarding'
    | '/settings'
    | '/society-pulse'
    | '/join/$code'
    | '/'
    | '/call/$roomId'
    | '/events/$eventId'
    | '/recaps/$recapId'
    | '/requests/$requestId'
    | '/societies/$societyId'
    | '/calls'
    | '/events'
    | '/requests'
    | '/societies'
  id:
    | '__root__'
    | '/_authenticated'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/committee'
    | '/_authenticated/communications'
    | '/_authenticated/inbox'
    | '/_authenticated/my-societies'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/society-pulse'
    | '/join/$code'
    | '/_authenticated/'
    | '/_authenticated/call/$roomId'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/recaps/$recapId'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/societies/$societyId'
    | '/_authenticated/calls/'
    | '/_authenticated/events/'
    | '/_authenticated/requests/'
    | '/_authenticated/societies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-societies': {
      id: '/_authenticated/my-societies'
      path: '/my-societies'
      fullPath: '/my-societies'
      preLoaderRoute: typeof AuthenticatedMySocietiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/society-pulse': {
      id: '/_authenticated/society-pulse'
      path: '/society-pulse'
      fullPath: '/society-pulse'
      preLoaderRoute: typeof AuthenticatedSocietyPulseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/call/$roomId': {
      id: '/_authenticated/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof AuthenticatedCallRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/': {
      id: '/_authenticated/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AuthenticatedCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recaps/$recapId': {
      id: '/_authenticated/recaps/$recapId'
      path: '/recaps/$recapId'
      fullPath: '/recaps/$recapId'
      preLoaderRoute: typeof AuthenticatedRecapsRecapIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/societies/': {
      id: '/_authenticated/societies/'
      path: '/societies'
      fullPath: '/societies/'
      preLoaderRoute: typeof AuthenticatedSocietiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/societies/$societyId': {
      id: '/_authenticated/societies/$societyId'
      path: '/societies/$societyId'
      fullPath: '/societies/$societyId'
      preLoaderRoute: typeof AuthenticatedSocietiesSocietyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMySocietiesRoute: typeof AuthenticatedMySocietiesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocietyPulseRoute: typeof AuthenticatedSocietyPulseRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCallRoomIdRoute: typeof AuthenticatedCallRoomIdRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedRecapsRecapIdRoute: typeof AuthenticatedRecapsRecapIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedSocietiesSocietyIdRoute: typeof AuthenticatedSocietiesSocietyIdRoute
  AuthenticatedCallsIndexRoute: typeof AuthenticatedCallsIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedSocietiesIndexRoute: typeof AuthenticatedSocietiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMySocietiesRoute: AuthenticatedMySocietiesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocietyPulseRoute: AuthenticatedSocietyPulseRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCallRoomIdRoute: AuthenticatedCallRoomIdRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedRecapsRecapIdRoute: AuthenticatedRecapsRecapIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedSocietiesSocietyIdRoute: AuthenticatedSocietiesSocietyIdRoute,
  AuthenticatedCallsIndexRoute: AuthenticatedCallsIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedSocietiesIndexRoute: AuthenticatedSocietiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
